name: "New Feature Request"
description: "Suggest a new feature for the project"
labels: ["enhancement"]
assignees: []
type: feature

body:
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the new feature you would like to request.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A detailed description of the feature.
      placeholder: Enter the feature description

  - type: textarea
    id: technical_approach
    attributes:
      label: Technical Approach
      description: How do you propose to implement this feature? (Class, design patterns, etc.)
      placeholder: "Utilisation of a Mediator pattern to manage interactions between components."

  - type: checkboxes
    id: definition_of_done
    attributes:
      label: Definition of Done
      options:
        - label: "Unit tests/functional tests written and passing"
        - label: "Documentation updated"
        - label: "Code follows project coding standards"
        - label: "Feature has been reviewed and approved by maintainers"
        - label: "Feature works as expected and does not introduce new bugs"
    validations:
      required: true
