name: Raytracer

env:
  EXECUTABLES: Raytracer

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted ]
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Create build directory
        run: mkdir -p build

      - name: Install Libconfig++
        run: apt-get update && apt-get install -y libconfig++-dev
        timeout-minutes: 5

      - name: Configure CMake
        run: cd build && cmake ..
        timeout-minutes: 5

      - name: Compile all binaries
        run: cd build && cmake --build . -j$(nproc)
        timeout-minutes: 5

  launch_tests:
    needs: build
    runs-on: [ self-hosted ]
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Create build directory
        run: mkdir -p build

      - name: Install GoogleTest
        run: apt-get update && apt-get install -y googletest libgtest-dev
        timeout-minutes: 5

      - name: Install Libconfig++
        run: apt-get update && apt-get install -y libconfig++-dev
        timeout-minutes: 5

      - name: Configure CMake
        run: cd build && cmake ..
        timeout-minutes: 5

      - name: Compile tests
        run: cd build && cmake --build . -j$(nproc)
        timeout-minutes: 5

      - name: Run tests
        run: cd build && ctest --output-on-failure
        timeout-minutes: 5
  linter:
    runs-on: [ self-hosted ]
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install clang-tidy
        run: apt-get update && apt-get install -y clang-tidy

      - name: Configure CMake for clang-tidy
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run linter
        run: |
          find . -not -path "./tests/*" -not -path "./build/_deps/*" \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-tidy -p build
        timeout-minutes: 10
  format:
    runs-on: [ self-hosted ]
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install clang-format
        run: apt-get update && apt-get install -y clang-format-20

      - name: Check code formatting
        run: |
          find . -not -path "./tests/*" \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-format-20 -style=file --dry-run --Werror
